### ISSUE TITLE
Signing transaction with @wallet issue

### ISSUE THREAD

**Issue by marpavlov2** [ton-connect/demo-telegram-bot#3]
Hi all,

we used this repository to create the Telegram Bot. We didn't use a redis for our project
1. Inside a `commands-handlers.ts` pTIme sendTransaction function we replaced an address with our smart contract address (production).
2. Changed CHAIN.TESTNET to CHAIN.MAINNET

Signing a transaction with ton keeper works, but using the Telegram @walllet produces the following error.
`This request has expired. Please request again.` 

How can we fix it?

Thanks in advance!

![image](https://github.com/ton-connect/demo-telegram-bot/assets/15014529/b1fb8a43-797c-47e6-b810-ca8098ef8936)

**Comment by priyanshhhh** [comment]
**Nice 🙂👍**

**Comment by siandreev** [comment]
That probably can happen if your transaction body is packed incorrectly. Try sending the same request with @tonconnect/ui in the [demo-dapp-with-react-ui](https://github.com/ton-connect/demo-dapp-with-react-ui)
